DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;
DROP TABLE IF EXISTS t4;
DROP TABLE IF EXISTS t5;
DROP TABLE IF EXISTS t6;
DROP TABLE IF EXISTS t7;
DROP TABLE IF EXISTS t8;
DROP TABLE IF EXISTS t9;
DROP TABLE IF EXISTS t10;
DROP TABLE IF EXISTS t11;
DROP TABLE IF EXISTS t12;
DROP TABLE IF EXISTS t13;
DROP TABLE IF EXISTS t14;
DROP TABLE IF EXISTS t15;
DROP TABLE IF EXISTS t16;

CREATE TABLE t1 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t2 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t3 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t4 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t5 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t6 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t7 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t8 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t9 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t10 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t11 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t12 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t13 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t14 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t15 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);

CREATE TABLE t16 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(1024)
);
